
name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Deploy to Cloud Functions
      uses: google-github-actions/deploy-cloud-functions@v1
      with:
        name:  flight-ml-ingest-snapshot-2
        entry_point: ingest
        source_dir: src
        runtime: python310
        event_trigger_type: google.pubsub.topic.publish
        event_trigger_resource: projects/aia-ds-accelerator-flight-1/topics/ingest-flight-snapshot-trigger
