name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'aia-ds-accelerator-flight-1@appspot.gserviceaccount.com'

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: aia-ds-accelerator-flight-1
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
  


    - name: Deploy to Cloud Functions
      uses: google-github-actions/deploy-cloud-functions@v1
      with:
        name:  flight-ml-ingest-snapshot-1
        entry_point: ingest
        source_dir: src
        runtime: python310
        event_trigger_type: google.pubsub.topic.publish
        event_trigger_resource: projects/aia-ds-accelerator-flight-1/topics/ingest-flight-snapshot-trigger

